development:
  adapter: postgresql
  database: ministrandi_development
  encoding: unicode
  reconnect: true
  min_messages: warning
  pool: 15
  timeout: 5000
  username: juarezlustosa

test: &test
  adapter: postgresql
  database: ministrandi_test
  encoding: unicode
  reconnect: true
  min_messages: warning
  pool: 15
  timeout: 5000
  username: juarezlustosa

production:
  adapter: postgresql
  database: ministrandi_production
  encoding: unicode
  reconnect: true
  min_messages: warning
  pool: 15
  timeout: 5000
  username: juarezlustosa

cucumber:
  <<: *test
